### ISSUE TITLE
правки Lesson 7-8

### ISSUE THREAD

**Issue by EkaterynaB** [EkaterynaB/EkaterynaB.github.io#10]
Залила ДЗ 7-8)))

**Comment by sergolius** [comment]
Зачет

**Comment by sergolius** [comment]
## 320xp:
1. http://joxi.ru/n2Y8YpxcyE3nm6
   html width: 475px
   правая кнопка карусели не кликабельна.
   нужно задать им zIndex.
2. http://joxi.ru/V2VnG0OCqjgz2v
   При наведении на меню, список находится ниже указателя текущей страницы.
   Возникает эффект смещения.
3. http://joxi.ru/vAWDVEnHldv8rW
   Должны быть полупрозрачными.
4. http://joxi.ru/l2Zv3zkTLob92J
   Не правильный цвет, размер теней.
5. http://joxi.ru/Vm6ykjoCbMOxrZ
   Уголок отображается только на самом большем исходнике.
6. http://joxi.ru/p278gpPc8wMjA7
   Цвет шрифта должен быть не черным.
   Отступ между ".updates__titile" и ".updates__author".

## 480px:
1. http://joxi.ru/MAj0Rnqtobzyme
   Отсутствует тень у стрелочек карусели.
2. http://joxi.ru/v29Q7bpIN57y2G
   Отсутствует нижняя тень у блока.
3. http://joxi.ru/VrwopGdCk6Z9rX
   Нужно вертикально выровнять блок с текстом относительно картинки.
4. http://joxi.ru/Q2KnjkQCqBzvmj
   Нет двойного бордера.
   Нет фонового цвета у блока категорий.

## 768px:
1. http://joxi.ru/ZrJVExMiD4JKrj
   Имелась ввиду подсветка при наведении.
2. http://joxi.ru/LmGV7OMiDayVrl
   Нижняя тень отсутствует.
3. http://joxi.ru/E2pvM7qTx3d5rY
   Нужно выровнять шрифты.
   Мелкое, но мозолит глаз.
4. http://joxi.ru/krDp7aMcxaMGrp
   Этот блок должен быть видимым на 960px и больше.

## 960px:
1. http://joxi.ru/Y2Lj815cqZwVr6
   Будет чудесно, если добавить пару точек для стрелочек.
   Что бы они не прилипали к экрану меньше 1500px шириной
2. http://joxi.ru/Dr8KozMivBZ8A6
   У текста не хватает тени.
3. http://joxi.ru/bmooBygCdZMMmy
   У блока Категории или Футера не хватает тени.

p.s. Попробуйте заменить фоновые изображения на более качественные, без артефактов (квадратиков).

**Comment by EkaterynaB** [comment]
Исправила замечания + добавила поддержку для IE8+

**Comment by sergolius** [comment]
1. http://joxi.ru/l2Zv3zkTLgd72J
   Съехала аватарка
2. http://joxi.ru/brRDdqZH6KZB21
   Цвет текста должен быть не черный.
3. http://joxi.ru/eAOq58dFDMWEmo
4. цвет фона
5. тень текста
6. http://joxi.ru/ZrJVExMiDXdzrj
   На треугольнике не хватает тени.
   `:after, :before` хорошо, но иногда придется в них пихать картинки.
7. http://joxi.ru/J2beJdqc5PNNm6
   915px немного разъехалось

**Comment by EkaterynaB** [comment]
не совсем поняла пункт 1 и 7. 
по 1-му пункту: если имелось ввиду, что фото сместилось на пару пикселей в сторону, тогда ok, исправила. 
по 7-му: вроде, согласно макета, так и должно быть, хотя... может я чего-то не замечаю(

**Comment by sergolius** [comment]
1 - верстка; 2 - изображение.
1. http://joxi.ru/823OgGoSX9Y02O
   тень под лого.
2. http://joxi.ru/5mdkGKqIK3gMr1
   не хватает нижнего бордера и слабой тени.
3. http://joxi.ru/52a1JWlhWEXJ20
   не хватает белых бордеров.

Зачет.

**Comment by EkaterynaB** [comment]
Спасибо за правки) Все исправила. правда, возник вопрос: border же можно "нарисовать" через box-shadow.
Как будет правильнее добавить border:
border-top: 1px solid #fefefe;
border-bottom: 1px solid #fefefe;
outline: 1px solid #e6e6e6;
или
    box-shadow: 0 0 0 1px #fefefe, 0 0 0 2px #e6e6e6; (правда, при этом варианте пришлось бы добавить родителю margin-bottom: 2px)

**Comment by sergolius** [comment]
Помните, что некоторым свойствам из CSS3 все еще следует задавать варианты с префиксом.
Например `box-shadow`: `-webkit-box-shadow`, `-moz-box-shadow`.
Но это работу можно переложить на плагин "autoprefixer".

По html тегам.
nav - главная, вспомогательные навигации (список ссылок/якорей которые куда-то ведут).
Он не предназначен для индикаторов карусели.
aside - сайдбар. 
`aside.info__box.info__box--black` возможно лучше было использовать `article`, если сомневаетесь какой тег нужно использовать - `div` всегда придет на помощь :)

Зачет.

**Comment by EkaterynaB** [comment]
Исправила
