### ISSUE TITLE
правки по ДЗ

### ISSUE THREAD

**Issue by kateryna06** [EkaterynaB/EkaterynaB.github.io#2]
http://joxi.ru/LQ2Kk3qhYa0y2j лучше избегать использование <br> в своем коде

и если ты проинспектируешь и удалишь ее, то ничего визуально не изменится, а следовательно она тут лишняя ))

**Comment by kateryna06** [comment]
ЗАЧЕТ

**Comment by kateryna06** [comment]
пропустила один момент.

Нужно убрать все hr и сделать линии другим способом. Если не придумаешь как. напиши я подскажу ))

**Comment by EkaterynaB** [comment]
залила новую версию работы без hr)))

**Comment by kateryna06** [comment]
можно конечно и так оставить как ты добавила класс line на параграфы. Но будем рассуждать логически. У нас есть 4 визуальных блока http://joxi.ru/jnAylD6IpXYk2Z которые разделены горизонтальной линией. Следовательно, было бы правильно добавить класс line не на параграф, а обернуть твой контент в див и на него уже добавить бордер. На который ты добавишь отступы, а следовательно с других тегов у тебя уберутся лишние стили.

Прежде чем начать верстать страницу, ты должна на нее посмотерть и представить как ты ее будешь делать. Увидеть и выделить логические блоки, какие есть похожие блоки и т.д. и тогда уже приступать к верстке. Лучше потратить несколько минут, чтоб это себе все представить, чем сразу начать быстро делать, а потом переделывать.

**Comment by kateryna06** [comment]
правки по css: сначала пишутся общие стили,  а потом уже стили для классов. И все стили должны быть структурированы. Т.е., например, есть блок с классом box, а за ним блок с классом media. Так вот стили для класса box не должны идти после стилей для класса media или быть как-то перемешаны

**Comment by EkaterynaB** [comment]
Спасибо за правки, решила я переписать код, а то "каша" получилась))) 
- добавила 4 div .block;
- добавила классы question и answer (удалила класс info);
- переписала стили;
  Извини за двойную работу

**Comment by kateryna06** [comment]
1. http://joxi.ru/lJ2bdoXFdXnEr6 вот эти стили лишние. Ты же эти отступы можешь добавить на свой класс block и таким образом если добавится другой тег, то он не будет прилипать с краю
2.    background: #eeeeee; это не ошибочная запись, то лучше писать сокращенную версию     background: #eee; (сокращаем до 3х символов тогда, когда у нас символы повторяются)

**Comment by EkaterynaB** [comment]
1. убрала левый отступ у абзацев (оставила стиль - выравнивание по центру), уменьшила левый margin в списке, добавила отступ к блокам.
2. переписала на сокращенные версии название цветов.
   PS вопрос: когда мы указываем цвет, лучше придерживаться одного стиля или можно использовать разный (white, #fff, rgba(0,0,0,0))?
   Спасибо)

**Comment by kateryna06** [comment]
ЗАЧЕТ

PS вопрос: когда мы указываем цвет, лучше придерживаться одного стиля или можно использовать разный (white, #fff, rgba(0,0,0,0))? Спасибо)

rgba(0,0,0,0) - его я обычно использую когда нужно задать прозрачность. Т.к. последний символ отвечает за прозрачность. 

white - таким образом ты можешь задать или белый или черный цвет. Т.к. для красного, например, существуюет множество оттенков. 

#fff - сокращенно пишем, только если это позволяет цвет. Например, ed1c24 такой цвет мы никак не сократим

Надеюсь я ответила на твой вопрос ))

**Comment by EkaterynaB** [comment]
Да, спасибо, ответила)))

**Comment by EkaterynaB** [comment]
залила д/з

**Comment by EkaterynaB** [comment]
попыталась сделать bonus, чувствую намудрила!!!))))
