### ISSUE TITLE
JS exam

### ISSUE THREAD

**Issue by EkaterynaB** [EkaterynaB/EkaterynaB.github.io#21]

**Comment by sergolius** [comment]
Мелкие правки.

## 320px
1. http://joxi.ru/v29Q7bpIOz5d2G
   Скругленные углы
2. http://joxi.ru/n2Y8YpxcRZE0m6
   Отцентровать кнопку

## 768px
1. http://joxi.ru/DmBX7KPijzGxAP
   Начиная с "планшетного" разрешения экрана не хватает нижнего отступа в футере
2. http://joxi.ru/Q2KnjkQC0wKRmj
   Шрифт в инпуте

## 960px
1. http://joxi.ru/xAeG8ZMiZgw8my
   Нужно немного выровнять текст по высоте
2. http://joxi.ru/52a1JWlhWbjq20
   Выравнивание контента элементов карусели

**Comment by sergolius** [comment]
По факту исправления правок - Зачет.

**Comment by EkaterynaB** [comment]
Все исправила

**Comment by sergolius** [comment]
Зачет.
