### ISSUE TITLE
правки Lesson3 

### ISSUE THREAD

**Issue by kateryna06** [EkaterynaB/EkaterynaB.github.io#3]
1.  как правило на body задается font основного текста, т.е. параграфов. Ты указала на body line-height 30px, а потом для параграфа пишешь 21px. Так вот, это line-height с параграфа убираем и задаем его на body. Теперь про font-family но body. В дизайне используется кастомный шрифт, который есть не на всех пк. По этому лучше после него не только указать семейство шрифтов, но и стандартный шрифт, чтоб браузер знал какой ему использовать, в случае если не найдет того, что ты задала. Т.е. у тебя будет запись "Open Sans", Arial, Helvetica sans-serif; Можно и не дописывать Helvetica, но лишней она не будет ))
2. http://joxi.ru/1bmoyebHVB8RAy смотри как у тебя подсвечивается ссылка на логотипе. У тебя это вся лишняя актиная область, а такого не должно быть. И как правильно логотипы задаются через background. Т.е. картинку логотипа убираем с html и вешаем ее бекграундом. Также в самой ссылке прописывается название логотипа, которое потом скрывается стилями (не поймешь как, пиши в скайп подскажу) - это больше для сео нужно. 
3. ты задала активное состояние для ссылок в меню Но как мы знаем что есть еще и ховерное состояние и оно обычно схоже с активным состоянием. Было бы отлично увидеть и ховер )))
4. пишешь слишком длинные пути в стилях. "aside ul li" можно написать просто "aside li" Точно также и для ссылок в сайтбаре "aside ul li a" можно записать "aside ul a" 
5. Ты картинку обернула просто в див  и для этого дива задала стили. Так делать не желательно, в смысле не добавлять никакой класс. У тебя же может добавиться еще блок и все стили для этого дива применятся. По этому картинку можно обернуть в тег figure или добавить на этот див какой-нибудь класс и стили прописать для этого класса. 
6. Если проинспетируешь свою картинку(велосипед), то увидишь что показывается справа какой-то отступ. Иногда он бывает сбоку, а иногда и снизу. Чтоб такого не было (а могут вылезти всякие бажки) то для картинки прописывают следующие стили display:inline-block vertical-align:top И все лишние отступы с каритнки пропадают. 
7. Теперь твой основной контент. http://joxi.ru/Ra2XjgYfRXx7rg ты для параграфов прописываешь такие отступы, что немного не правильно. Если ты добавишь еще один параграф, то во-первых у тебя нижний отступ у первого параграфа съесть верхний отступ у второго т.к. ты задала нижний и верхний маржин, а маржини перекрываются. А во-вторых, будет сильно большое расстояние между параграфа. Вывод: нужно твой параграф обернуть в див на который ты задашь отступы, а на параграф нужно будет задать только нижный отступ, чтоб в случае добавления еще одного они не прилипли друг к другу. 
8. Футер. Если ты уже начала использовать размеры в пикселях, то нужно и дальше их придерживаться. По этому ширина твоей навигации в футуру тоже должна быть в пикселях. 
9. "footer nav ul a" эту запись тоже можно сократить. И в футере тоже добавить нужно ховерные состояния для ссылок. 

Почему не нужно писать длинные пути? Потому что проекты бывают большие, а у тебя будут похожие блоки, но ,например, на какой-то другой странице он у тебя будет чем-то отличаться и тебе нужно будет перебить стили. "footer nav ul a" а у тебя тут уже длинный путь и тебе придется или дописывать или еще один тег или прописать от какого-то класса и получится целый поровоз из тегов )) По этому все что можно немного сократить - пишем сокращенно. 

А в общем работа выполнена неплохо

**Comment by EkaterynaB** [comment]
Спасибо за подробные объяснения, они оооочень полезны и вносят ясноть. Я, вроде бы, все поправила, но ошибок не исключаю)))

**Comment by kateryna06** [comment]
1) http://joxi.ru/BLmGOKphQeoGml ох намудрила тут )) делаем просто ссылку с классом logo и все и не нужно столько оберток

2) когда делаешь ховер в меню, то бердеры у тебя должны накладываться друг на друга, а сейчас у тебя он удваивается. http://joxi.ru/4vAWEqeup181mW вот так должно быть

3) http://joxi.ru/8ZrJxRjuq9Kl2j зачем ты сюда пишешь display:inline-block а vertical-align ?? 

4) http://joxi.ru/gkrDaWkUQEepmp все что на ссылке светится синим - это все активная кликабельная область. А кликабельным должен быть только текст. И по бокам из за паддингом тоже все кликабельно.

**Comment by EkaterynaB** [comment]
попытка номер ....надцать)))

**Comment by kateryna06** [comment]
1) для http://joxi.ru/QeAO8x6h0v58ro лучше писать text-indent: -9999px; чтоб уж наверняка

в остальном все правильно

ставлю ЗАЧЕТ но ты залей плиз это изменение
