### ISSUE TITLE
правки Lesson 3 bonus

### ISSUE THREAD

**Issue by kateryna06** [EkaterynaB/EkaterynaB.github.io#4]
1. Еще одно важное правило. line-height никогда не может быть font-size и желательно его делать на 2 пикселя больше чем размер шрифта. Потому что в некоторых браузерах буквы могут обрезаться.
2. неправильно указан font-family. Проверь плиз с дизайном какой должен быть.
3. лишний класс email на ссылке. logo тоже класс лишний, раз от него не прописано никаких классов
4. инспектируем ссылку с логотипом и видим, что она не подсвечивается, что не есть гуд. Если блоки сделаны правильно, они должны подсвечиваться в инспекторе. Возможно немного стоит переделать хэдер. )))
5. для блока country все маржины можно объединить и записать в 1 строку. 
6. Все эти блоки со странами должны быть ссылками. Мы же находимся на сайте какого-то тур оператора и выбираем страну, следовательно, по логике, когда мы кликнем на блок со страной мы перейдем на страницу с описанием. А сейчас никуда мы не перейдем и ничего не узнаем про эту страну (( 

Сейчас я тебя немножко огорчу. Ты умничка что сделала блоки с красивым ховером, но с большей вероятностью эти картинки нужно было вставлять не бекграундом, а картинками. Объясню почему, если клиент захочет добавить какую нибудь другую страну, то ему будет проще просто добавить картинку и текст, и не нужно ему будет лезть в код, добавлять новые классы и в стилях прописывать картинку. Можешь не переделывать, но на будущее нужно учесть, все что ты делаешь будет отдаваться клиенту, и ему должно быть максимально удобно что-то добавлять/ удалять и без ущерба для сайта ))))

**Comment by EkaterynaB** [comment]
ничего страшного, тот не ошибается, кто ничего не делает))) Мне хотелось попробывать сделать интересный ховер, с background я понимаю как, а вот с img, пока только догадываюсь)

**Comment by EkaterynaB** [comment]
В д/з №4 размещение колонок с одинаковой высотой, решила реализовать с помощью Метод 3 — использование обертывающих блоков (из статьи, которую нам кидали вместе с д/з), но этот метод, мне кажется, не идеален (особенно, если убрать одну из колонок).

**Comment by kateryna06** [comment]
1)  http://joxi.ru/8ZrJxRjuq94l2j лучше писать width:100%

2) http://joxi.ru/dp27pjEhMow4A7 зачем ты сюда strong впихнула? Он не нужен тут. Ты ж уже в картинку написала этот текст

3) http://joxi.ru/XEA40GbsLw7vAb зачем тут лишние классы?? 

4) http://joxi.ru/LQ2Kk3qhn4KR2j не можем мы тут просто оставить тег section без класса. Это очень распространенные тег и он может встретиться еще на другой странице и к нему применятся твои свойства, которые, скорее всего, не нужны ему будут на другой странице

5) http://joxi.ru/wRmzjDQfq0BpmO нельзя глобально для ссылок прописывать display:block Это свойство сделает ссылку кликабельной по всей ширине блока в котором она находится, а это неправильно. Если тебе нужно чтоб ссылка было блочной, то тогда нужно прописать это свойство от родителя

6) http://joxi.ru/752aW9eHL4Oqr0 тут картинку можно запихнуть в див и ты избавишься от многих свойств на классе frame

**Comment by EkaterynaB** [comment]
старалась не мудрить))))

**Comment by kateryna06** [comment]
1) http://joxi.ru/4vAWEqeup3dDmW если ты хочешь скрыть текст, то можно или обнулять размер шрифта или через text-indent но в принципе. strong тут не нужен

ЗАЧЕТ
