### ISSUE TITLE
правки Lesson 4

### ISSUE THREAD

**Issue by EkaterynaB** [EkaterynaB/EkaterynaB.github.io#5]
залила ДЗ 4, жду правок))))

**Comment by kateryna06** [comment]
1) http://joxi.ru/aD2PNkyFQLMxr3  не так у нас по дизайну Тебе нужно было везать картинку вот так http://joxi.ru/Ra2XjgYfE80qrg 

2) http://joxi.ru/wRmzjDQfqBWDmO лишний див. Класс вешаем на ссылку и прописываем стили

3) http://joxi.ru/4DmBK5RH9GNb2P эти 2 дива делаем не через absolute. По хорошему ты эти 2 дива должна обернуть в общий див и сделаеть ему float:right и все. И дальше норм прописывать стили для тех блоков

4) http://joxi.ru/WKAx0DMsdNMwA8 цвет текста должен быть везде одинаковый 

5) http://joxi.ru/LQ2Kk3qhnKLb2j ширину убираем и выравниваем отступами. 

6) http://joxi.ru/BLmGOKphQ6woml если блок занимает всю ширину родителя то лучше писать width 100% Посмотри где еще можно это исправить

7) http://prntscr.com/91hnih а откуда взяла такие стили? не было такого в дизайне. Не нужно придумывать состояния. Если видишь что их нет, то в таком случае пишется менеджеру и говорится что нет таких и таких состояний для элементов и он уже узнает у клиента как должно быть.

8) http://joxi.ru/el2ZzGYhKJ7O2J в хорошем макете левый и правый отступы должны быть одинаковые, ну или отличаться на пару пикселей. Лучше сделать одинаково

9) http://joxi.ru/WKAx0DMsdNKaA8 убираем, а стрелочку вешаем бекграундом на ссылку

10) http://joxi.ru/wGrq8DBhoLRpAz не должно быть бордеров у ссылки

11) http://joxi.ru/E5mdKVnHjwqgr1 одинаковые стили, а разные классы - непорядок

12) http://joxi.ru/4zAN7XBUQR1pr9 с заголовков убираем боковые отступы

13) http://joxi.ru/BLmGOKphQ6ZKml куда потеряла тенюшку и нижний бордер?

14) http://joxi.ru/aD2PNkyFQOWNr3 не должно быть этого отступа. Было показано в дизайне откуда должна начинаться страница

15) ох ты и любительница допридумать дизайн http://joxi.ru/QY2L1ODcyZv6A6 это не слайдер, а обычный банер. Если б был слайдер, то дизайнер бы написовал переключалку и еще картинки вставил бы

Надеюсь ничего не упустила

**Comment by EkaterynaB** [comment]
"самодеятельность" убрала , правки внесла

**Comment by kateryna06** [comment]
1) http://prntscr.com/92akxg ссылка должна светиться на всю высоту

2) http://joxi.ru/8ZrJxRjuaQbG2j не хорошо так писать. Для списка мы обнуляем только отступы. А если добавишь какой-то другой спискои  не задашь font для текста у тебя ничего не будет видно ((

3) http://prntscr.com/92alzv тут она у тебя вся светится от отступе. А должна она светиться у тебя вот так http://prntscr.com/92amag

4) http://joxi.ru/gV2V0JvswBBwrv что тут делают спаны?

**Comment by EkaterynaB** [comment]
Одни испарвления есть)))

**Comment by EkaterynaB** [comment]
одни правки готовы)))

**Comment by kateryna06** [comment]
1) http://joxi.ru/Bv29bzyh7wO3AG a line-height ты пишешь на ul. Давай писать все в одном месте 

2) http://joxi.ru/Ra2XjgYfNW7nrg не должно быть такой большой тени внизу

**Comment by EkaterynaB** [comment]
Переделала)))

**Comment by kateryna06** [comment]
ЗАЧЕТ

**Comment by kateryna06** [comment]
Кать, закрой плиз этот issue чтоб от не отвлекал ))
