### ISSUE TITLE
lesson 5 table

### ISSUE THREAD

**Issue by kateryna06** [EkaterynaB/EkaterynaB.github.io#6]
1) http://joxi.ru/jgmvMDVh7OMXra не должно быть пустых тегов

2) http://joxi.ru/4DmBK5RH9GWd2P в этом квадратике должно быть 4 квадратика http://joxi.ru/LVm6jE3fOobjmZ

**Comment by EkaterynaB** [comment]
пустые теги убрала, квадратики разъединила)

**Comment by kateryna06** [comment]
ЗАЧЕТ

**Comment by EkaterynaB** [comment]
УРААААА!)))
