### ISSUE TITLE
lesson 5

### ISSUE THREAD

**Issue by kateryna06** [EkaterynaB/EkaterynaB.github.io#7]
1) http://joxi.ru/lbrRqynC5X3DA1 2 раза обнуляешь стили

2) http://joxi.ru/vDr8zp9hxBy726 неа, ширину пишем 100% иначе когда человек откроем с больим разрешением будет бедулька 

3) http://joxi.ru/E5mdKVnHjwYyr1 нет в дизайне бордеров

4) http://joxi.ru/Bv29bzyhVxqqAG картинку вешаем на бг

5) http://joxi.ru/Y82QJ14sYnbkAd сюда лучше добавить класс и прописать стили от класса. а то вдруг местами захотят поменять и будет бедулька

6) http://joxi.ru/QeAO8x6h03qGro на ховер добавить убирание underline 

7) http://joxi.ru/BLmGOKphQ65Nml в задании было сказано что этт блок должен выравниться и по вертикали по центру. а у только выравнивание по горизонтали

8) http://joxi.ru/QY2L1ODcyZg9A6 где ты нашла в псд что у него такой font-weight. Выравнять лучше не через line-height а паддингами. Это не очень хорошо так выравнивать текст и нужно применять его очень обдуманно. 

9) http://joxi.ru/QY2L1ODcyZg9A6 если ты центрируешь текст по центру. то не нужно добавлять еще боковые отступы. Это косяк дизайна

10) http://joxi.ru/DBA0qJbCGO7Wry высоту убираем

11) у тебя для before и для after одинаковое значение bottom. И его нужно написать в кучу к общим стилям

12) http://joxi.ru/WL21gqJT5dxkrX и padding-right нужно задать 

13) http://joxi.ru/lbrRqynC5XolA1 неправильный цвет

**Comment by EkaterynaB** [comment]
исправила, надеюсь все)

**Comment by kateryna06** [comment]
1) http://joxi.ru/752aW9eH8lD5r0 не нужна тут ширина. По бокам у тебя не должно быть активной области

2) http://joxi.ru/lJ2bdoXF3q5Wr6 не хорошо писать на блок font-size:0 Надеюсь поняла из чата ))

3) http://joxi.ru/752aW9eH8lBDr0 бордер нужно повесить на твой правый блок

4) http://joxi.ru/DBA0qJbCg19Qry зачем тебе тут отрицательный отступ?

5) http://joxi.ru/QeAO8x6hJvoGro нужно задать font

6) wrapper нужно выровнять через display:table-cell

Пока на этом все, а дальше посмотрим ))

**Comment by EkaterynaB** [comment]
спасибо за правки, за терпение и отличное объяснение. Жду следующих правок))))

**Comment by kateryna06** [comment]
1) http://joxi.ru/lJ2bdoXF3WoBr6 бордер не должен прилипать к краям. Там есть отступ в пару пикселей. 

2) http://joxi.ru/Ra2XjgYfNWVnrg еще одна болячка появилась. Не нужно лепить этот clearfix везде где только можно. Вот тут он не нужен вообще. 

3) http://joxi.ru/JMAjnDefzOwDAe  не должен line-height быть меньше font-size

**Comment by EkaterynaB** [comment]
Переделала.
Это ты еще не заметила лишний .clearfix в css. Вот сколько я их наплодила))) 
Будем с этим бороться)))

**Comment by kateryna06** [comment]
ЗАЧЕТ

с хедера тоже можно было убрать. Вообщем на будущее. Лучше написать 2 строчки кода, чем добавлять классы в html
