### ISSUE TITLE
правки Lesson 6

### ISSUE THREAD

**Issue by EkaterynaB** [EkaterynaB/EkaterynaB.github.io#8]
залила дз 6, жду правок)))

**Comment by kateryna06** [comment]
1) http://joxi.ru/Vm6jE3fxVv1VmZ обрезалась иконка

2) поубирать clearfix!!!!!

3) http://joxi.ru/nAylD6IXywNL2Z классы иконок лучше прописать от родителя, мало ли что может быть еще с таким классом

4) http://joxi.ru/12MynxH4qkx02J тоже флоатаем вправо и с родителя убирается левый отступ

5) http://joxi.ru/Vm6jE3fxVvENmZ можно все выровнять и без отрицательных отступов

6) http://joxi.ru/L21gqJT6G0Z7rX ну и зачем тут этот спан?

7) http://joxi.ru/ZrJxRju13nzR2j недоровняла текст

8) http://joxi.ru/E2p7DnUBOGMpmY ну и что это за безобразие?

9) http://joxi.ru/vAWEqeukjOQvmW поняла? 

10) http://joxi.ru/eAO8x6h4wklpro выровнять нужно 

11) http://joxi.ru/KAgRDJfgnKak2l все выравнивается

12) http://joxi.ru/a2XjgYfy04olrg поняла?

13) и с .product аналогичная ситуация

14) http://joxi.ru/Dr8zp9hkZM6p26 должна быть ссылкой весь блок а не части

15) http://joxi.ru/Vm6jE3fxVvWKmZ ох начала выдумывать что то

**Comment by EkaterynaB** [comment]
одни правки готовы)))

**Comment by kateryna06** [comment]
1) http://joxi.ru/J2bdoXF44p4gr6 не теряем семейство шрифтов

2) http://joxi.ru/Q2Kk3qh99KLY2j если тут задаешь табличные свойства, то дочерние элемнты тоже должны иметь табличные свойства. А у тебя ссылки инлайно блочные. Чет надо с этим делать ))

3) http://joxi.ru/a2XjgYfyy8DMrg лишний класс. Если что у тебя есть родитель products

4) http://joxi.ru/V2V0Jvs00yK3rv забыла семейство шрифтов

5) http://joxi.ru/xAeZwXhYYwX0ry лишняя обертка

**Comment by EkaterynaB** [comment]
вторые правки готовы)))

**Comment by sergolius** [comment]
1. http://joxi.ru/p278gpPc8wBaA7
   Нужно отцентровать иконку, что бы отступ сверху равнялся отступу снизу. 
   При этом сохранить вертикальное выравнивание текста.
   Цвет текста должен быть синим.
2. http://joxi.ru/12M1Vy6h15jp2J
   При наведение на элемент списка скачет bullet/иконка.
3. http://joxi.ru/gmvRjMWcn4Yema
   Нужно выровнять элементы по высоте.
4. http://joxi.ru/VrwopGdCk6nvrX
   Что бы не использовать `.products a:nth-child(3n)`, лучше сделать так:
   ".products-inner" содержит ссылки и находится в ".products" (.products > .products-inner > a)

```
.products-inner {
margin: -18px 0 0 -30px;
}
.products a {
    float: left;
    margin: 18px 0 0 30px;
}
```
1. http://joxi.ru/Vm6ykjoCbMedrZ
   Нижний отступ нужно увеличить.
2. http://joxi.ru/5mdkGKqI0GEOr1
   "забыли пароль?" шрифт отличается от исходника.

**Comment by EkaterynaB** [comment]
.products-inner {
margin: -18px 0 0 -30px;
}
.products a {
    float: left;
    margin: 18px 0 0 30px;
}
это, конечно, "волшебство")))
Вроде все исправила....

**Comment by sergolius** [comment]
`.products-inner` достаточно одного :)

```
<div class="products-inner">
   <a class="#">
      ....
   </a>
   <a class="#">
      ....
   </a>
   <a class="#">
      ....
   </a>
</div>
```

Зачет.
