### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EkaterynaB** [EkaterynaB/EkaterynaB.github.io#9]
ДЗ 1 - 4 уже давно заждались правок

**Comment by sergolius** [comment]
Лучше использовать один тип кавычек или одинарные ' или двойные ".  
ДЗ 1 - Зачет.

**Comment by EkaterynaB** [comment]
Ok! Спасибо! В ДЗ 2-4 уже исправила.

**Comment by sergolius** [comment]
Правки к ДЗ №2:
1. Если при запросе имени нажать Cancel/Отмена, в консоли обнаружим ошибку:

``` javascript
Cannot read property 'toLowerCase' of null
```

Нужно проверять данные получаемые от пользователя или отказаться от форматирования имени.
2. Строка №10: 

``` javascript
i -= i;
```

Если во время заполнения массива именами сделать ошибку, оставить поле пустым или ввести пробел, то массив придется заполнять заново (с нулевого элемента).

**Comment by sergolius** [comment]
Правки к ДЗ №3:
1. Кавычки в js, css (' || ").

Что бы не проверять каждый аттрибут, предлагаю использовать перебор свойств объекта (https://learn.javascript.ru/object-for-in):

``` javascript
if (params.attributes) {
    for (var i in params.attributes) {
        if (params.attributes.hasOwnProperty(i)) {
            element.setAttribute(i, params.attributes[i]);
        }
    }
}
```

ДЗ №3 - Зачет.

**Comment by EkaterynaB** [comment]
ДЗ №2. Решила не отказываться от форматирования имени, а еще больше "замудрить" код. Надеюсь, не сильно намудрила)))

**Comment by sergolius** [comment]
ДЗ №2. Вводим одно имя, отмена, отмена, ошибка :)

**Comment by EkaterynaB** [comment]
понятно, чудо не произошло))) может в этот раз получится)

**Comment by sergolius** [comment]
ДЗ №2
Зачет.
